### ISSUE TITLE
YML parser

### ISSUE THREAD

**Issue by weeman1337** [benchomat/executor#1]
* structs
* from string
* from file `benchmarks.yml`

```yml
benchmarks:
  - name: load home page
    method: http
    type: time
    http:
      method: GET
      uri: https://example.com/
  - name: create user
    method: http
    type: time
    http:
      method: POST
      uri: https://example.com/users
      payload:
        type: json
        data:
          user:
            name: Steve
            email: steve@example.com
```
