### ISSUE TITLE
HTTP benchmark runner

### ISSUE THREAD

**Issue by weeman1337** [benchomat/executor#2]
* takes a struct from #1
* runs the http benchmark
* returns the struct

```yml
result:
  benchmark: load home page
  result: success
  time: 200
  error:
    status: 500
    payload: "bla bla"
```
